version: '3'

# there are multiple docker-compose files due to organic growth
# this one seems to be older and not so good maintained compared to /src/main/docker/docker-compose.yml
# TODO: started stripping this docker-compose file and migrate it to the /src/main/docker/docker-compose.yml

# NOTE: this docker compose file starts the artemis-server (as jar file) and the artemis-client in separate containers. This setup is aimed for development.
# If you want to start the whole Artemis application (server and client) in the same container, you need to specify a different service and
# you have to execute the command './gradlew -Pprod -Pwar clean bootWar && java -jar build/libs/*.war --spring.profiles.active=dev,artemis,bamboo,bitbucket,jira'

services:
  artemis-server:
    # compared to Dockerfile also installed fontconfig and ttf-dejavu
    # TODO: checkout building of artemis done inside the docker here?!
    command: sh -c "(apt update && apt install -y fontconfig ttf-dejavu graphviz || true) && ./gradlew buildJarForDocker && java -jar --add-exports java.naming/com.sun.jndi.ldap=ALL-UNNAMED build/libs/Artemis-*.jar"
    environment:
      #TODO: seems older as no athene and local profile omitted or on purpose?
      - SPRING_PROFILES_ACTIVE=dev,bamboo,bitbucket,jira,artemis,scheduling
    volumes:
      - ./:/server/
    working_dir: /server

  # TODO: figure out why there is a seperate artemis client
  # maybe for hot reloading or whatever?!
  artemis-client:
    command: sh -c "npm install && npm run start-docker"
    depends_on:
      - artemis-server
    image: node:14.17.6-alpine
    networks:
      - artemis
    ports:
      - 9000:9000
    volumes:
      - ./:/client/
    working_dir: /client

  artemis-mysql:
    volumes:
      - ./data/.db:/var/lib/mysql
