artemis:
    continuous-integration:
        url: https://bamboo.ase.in.tum.de
        # e.g. ga12abc
        # user: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
        # password: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
        # Enter a valid token generated in Bamboo giving Artemis full Admin access
        # token: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
        vcs-application-link-name: LS1 Bitbucket Server     # If the VCS and CI are directly linked (normally only for Bitbucket + Bamboo)
        empty-commit-necessary: true # Do we need an empty commit for new exercises/repositories in order for the CI to register the repo
        # The actual value of the notification token to check against in Artemis. This is the token that gets send with
        # every request the CI system makes to Artemis containing a new result after a build.
        # The token value you use for the Server Notification Plugin
        # artemis-authentication-token-value: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
