artemis:
    continuous-integration:
        url: https://bamboo.ase.in.tum.de
        vcs-application-link-name: LS1 Bitbucket Server     # If the VCS and CI are directly linked (normally only for Bitbucket + Bamboo)
        empty-commit-necessary: true # Do we need an empty commit for new exercises/repositories in order for the CI to register the repo
