artemis:
    continuous-integration:
        user: # e.g. ga12abc
        password:
        token: # Enter a valid token generated in Bamboo giving Artemis full Admin access
        # The actual value of the notification token to check against in Artemis. This is the token that gets send with
        # every request the CI system makes to Artemis containing a new result after a build.
        # The token value you use for the Server Notification Plugin
        artemis-authentication-token-value:
