# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        de.tum.in.www1.artemis: DEBUG
        tech.jhipster: DEBUG
        liquibase: ERROR

spring:
    devtools:
        restart:
            enabled: true
    jackson:
        serialization:
            indent-output: true
    datasource:
        url: jdbc:mysql://localhost:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    liquibase:
        contexts: dev
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false
    hazelcast:
        localInstances: true

server:
    # this address is passed to the CI systems for sending back notifications to Artemis
    # therefore depending on where these systems are hosted you have to change the url here
    # other possible values:
    # Artemis locally and CI inside Docker Containers: host.docker.internal:8080
    # Artemis locally and CI hosted on a Server on your network: LAN_IP_ADDRESS:8080
    url: http://localhost:8080 # Artemis and CI are running locally

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origin-patterns: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: artemis@localhost
        base-url: http://127.0.0.1:8080
    logging:
        use-json-format: false # By default, logs are not in Json format

# Properties to be exposed on the /info management endpoint
info:
    guided-tour:
        # Names of the tutorial groups that will be automatically added to newly created users
        course-group-students: 'artemis-artemistutorial-students'
        courseShortName: 'artemistutorial'
        tours:
            - code_editor_tour: 'test'
            - course_exercise_overview_tour: 'test'
            - programming_exercise_fail_tour: 'test'
            - programming_exercise_success_tour: 'test'
    # Specifies whether text assessment analytics service (TextAssessmentEventResource) is enabled/disabled
    # default value set to true for development environment
    text-assessment-analytics-enabled: true
