artemis:
    encryption-password: artemis_admin # LEGACY: arbitrary password for encrypting database values
    user-management:
        internal-admin:
            username: artemis_admin
            password: artemis_admin
