artemis:
    version-control:
        url: http://localhost:7990
        # e.g. ga12abc
        # user: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
        # password: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
        # VCS API token giving Artemis full Admin access.
        # token: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
        ssh-template-clone-url: ssh://git@localhost:7999/    # Url Stem for cloning via ssh, for gitlab use 'ssh://git@artemistest2gitlab.ase.in.tum.de:2222/'
        ssh-keys-url-path: /plugins/servlet/ssh/account/keys  # Url Path to access a users ssh keys, for gitlab this is '/-/profile/keys'
        ssh-private-key-folder-path: # the path to the folder in which the private ssh key file (e.g. id_rsa) is stored that can be used to clone git repos on the version control server
        # the password for the private ssh key
        # ssh-private-key-password: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
