artemis:
    user-management:
        use-external: true
        external:
            url: https://jira.ase.in.tum.de
            # e.g. ga12abc
            # user: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
            # password: PLEASE CHANGE THIS SECRET IN YOUR ENV OR application-local-secrets.yml
            admin-group-name: tumuser
        password-reset:
            credential-provider: TUMonline
            links:
                en: "https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/co_loc_password_reset.main?$ctx=design=ca2;header=max;lang=en"
                de: "https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/co_loc_password_reset.main?$ctx=design=ca2;header=max;lang=de"
