# ===================================================================
# GitLab specific properties: this file will only be loaded during startup if the profile gitlab is active
#
# This configuration overrides the application.yml file.
# ===================================================================
artemis:
    version-control:
        user: root
        password: artemis_admin # created in Gitlab Server Quickstart step 2
        token: artemis-gitlab-token # generated in Gitlab Server Quickstart steps 4 and 5
        ci-token: jenkins-secret-token # pre-generated or replaced in Automated Jenkins Server step 3
        health-api-token:
        ssh-private-key-password:
