artemis:
    version-control:
        url: http://localhost:7990
        # e.g. ga12abc
        # user: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
        # password: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV

        # VCS API token giving Artemis full Admin access.
        # token: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV

        # SSH for Git
        # SSH can be activated by setting <ssh-private-key-folder-path>

        # Url Stem for cloning via ssh
        ssh-template-clone-url: ssh://git@localhost:7999/
        # Url Path to access a users ssh keys
        ssh-keys-url-path: /plugins/servlet/ssh/account/keys
        # the path to the folder in which the private ssh key file (e.g. id_rsa) is stored
        # that can be used to clone git repos on the version control server
        # ssh-private-key-folder-path: IF NECESSARY CHANGE THIS VALUE IN YOUR application-local.yml or ENV

        # the password for the private ssh key
        # ssh-private-key-password: IF NECESSARY CHANGE THIS VALUE IN YOUR application-local.yml or ENV
