artemis:
    user-management:
        use-external: true
        external:
            url: http://localhost:8085
            # e.g. ga12abc
            # user: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
            # password: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
            admin-group-name: instructors
        password-reset:
            credential-provider: TUMonline
            links:
                en: "https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/co_loc_password_reset.main?$ctx=design=ca2;header=max;lang=en"
                de: "https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/co_loc_password_reset.main?$ctx=design=ca2;header=max;lang=de"
