# ===================================================================
# Local VC specific properties: this file will only be loaded during startup if the profile "localvc" is active
#
# This configuration overrides the application.yml file.
# ===================================================================
localvc:
    # A folder in which the local git repos are stored as bare repositories (using profile 'localvc' to save files locally instead of on Bitbucket or Gitlab).
    # In a multi node setup, this folder should be in a shared file system area (e.g. based on NFS), so that user can access the same files over multiple nodes.
    server-path: ./local-vc-server
