artemis:
    version-control:
        user: # e.g. ga12abc
        password:
        token: # VCS API token giving Artemis full Admin access.
        ssh-private-key-password: # the password for the private ssh key
