artemis:
    continuous-integration:
        url: http://localhost:8085
        # e.g. ga12abc
        # user: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
        # password: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV

        # Enter a valid token generated in Bamboo giving Artemis full Admin access
        # token: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV

        # If the VCS and CI are directly linked (normally only for Bitbucket + Bamboo)
        vcs-application-link-name: LS1 Bitbucket Server
        # Do we need an empty commit for new exercises/repositories in order for the CI to register the repo
        empty-commit-necessary: true
        # The actual value of the notification token to check against in Artemis. This is the token that gets send with
        # every request the CI system makes to Artemis containing a new result after a build.
        # The token value you use for the Server Notification Plugin
        # artemis-authentication-token-value: PLEASE CHANGE THIS SECRET IN YOUR application-local.yml or ENV
