# this profile contains the default variables for the docker compose setups
# TODO: check if this can be solved different without having to load the docker profile
artemis:
    course-archives-path: /opt/artemis/data/courses
    repo-clone-path: /opt/artemis/data/repos
    repo-download-clone-path: /opt/artemis/data/repos-download
    file-upload-path: /opt/artemis/data/uploads
    submission-export-path: /opt/artemis/data/exports

spring:
    datasource:
        url: jdbc:mysql://artemis-mysql:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC

server:
    # this address is passed to the CI/VCS systems for sending back notifications to Artemis
    # therefore depending on where these systems are hosted you have to change the url here
    # localhost:8080 for Artemis in container and CI/VCS outside of containers
    url: http://artemis-app:8080 # Artemis and CI/VCS are running in docker containers in the same docker network
