apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  labels:
  name: artemis-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /artemis
        pathType: Prefix
        backend: 
          service: 
            name: artemis
            port: 
              number: 8080
              #  tls:
              #  - hosts:
              #    - artemis-app.artemis.rancher.localhost
