# ----------------------------------------------------------------------------------------------------------------------
# Atlassian Setup
# ----------------------------------------------------------------------------------------------------------------------

services:
    jira:
        container_name: artemis-jira
        hostname: jira
        image: ghcr.io/ls1intum/artemis-jira:8.20.11
        pull_policy: always
        volumes:
          - artemis-jira-data:/var/atlassian/application-data/jira
        ports:
            - "8081:8080"
        networks:
            - artemis
    bitbucket:
        container_name: artemis-bitbucket
        hostname: bitbucket
        image: ghcr.io/ls1intum/artemis-bitbucket:7.21.4
        pull_policy: always
        volumes:
            - artemis-bitbucket-data:/var/atlassian/application-data/bitbucket
        environment:
            - SPRING_APPLICATION_JSON={"plugin":{"ssh":{"baseurl":"ssh://bitbucket:7999"}}}
        ports:
            - "7990:7990"
            - "7999:7999"
        networks:
            - artemis
    bamboo:
        container_name: artemis-bamboo
        hostname: bamboo
        image: ghcr.io/ls1intum/artemis-bamboo:8.2.5
        pull_policy: always
        volumes:
            - artemis-bamboo-data:/var/atlassian/application-data/bamboo
        ports:
            - "54663:54663"
            - "8085:8085"
        networks:
            - artemis

# TODO: either add ip addresses or use wildcard for agent to survive restarts and write this in docs
    bamboo-build-agent:
        container_name: artemis-bamboo-build-agent
        hostname: bamboo-build-agent
        image: ghcr.io/ls1intum/artemis-bamboo-build-agent:8.2.5
        volumes:
            - artemis-bamboo-build-agent:/var/atlassian/application-data/bamboo-agent
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - BAMBOO_SERVER=http://bamboo:8085
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
    artemis-jira-data:
        name: artemis-jira-data
    artemis-bitbucket-data:
        name: artemis-bitbucket-data
    artemis-bamboo-data:
        name: artemis-bamboo-data
    artemis-bamboo-build-agent:
        name: artemis-bamboo-build-agent
