services:
    artemis-app:
        platform: linux/x86_64
        image: ghcr.io/ls1intum/artemis
        build:
            context: ../../..
            dockerfile: src/main/docker/artemis/Dockerfile
        env_file:
            - ../resources/config-env/artemis.env # artemis profile and general spring configs
            - ../resources/config-env/artemis-dev.env # development profile
            - ../resources/config-env/artemis-dev-db.env # docker compose Development-DB profile
            - ../resources/config-env/artemis-override.env # local overrides and secrets (not under version control)
        ports:
            - 8080:8080
        networks:
            - artemis
        depends_on:
            - artemis-mysql
    artemis-mysql:
        extends:
            file: mysql.yml
            service: artemis-mysql

networks:
    artemis:
        driver: "bridge"
