version: '2.4'
services:
    artemis-mysql:
        # Use this for arm64 processors (and remove the platform: linux/x86_64
        # image: ubuntu/mysql:8.0-21.10_beta
        #TODO: newer versions of the mysql docker image supports arm64/v8
        # or change to mysql/mysql-server ("optimized" docker image by mysql team)
        image: mysql:8.0.27
        platform: linux/x86_64
        #TODO: check volume maybe enable for dev and disable or map it different for prod etc.
        # volumes:
        #     - ~/volumes/jhipster/Artemis/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=Artemis
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
